# ===========================================================================
# Password generation and secret storage
# The RDS password is never written by hand anywhere in this codebase.
# It is generated randomly and either stored in AWS Secrets Manager
# (when enable_secrets_manager = true) or kept only in the Terraform state
# (when running in a restricted environment).
# ===========================================================================

# Generate a strong random password for the RDS instance
resource "random_password" "db_password" {
  length           = 20
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"  # Characters compatible with RDS MariaDB
  min_upper        = 2
  min_lower        = 2
  min_numeric      = 2
  min_special      = 2
}

# ---------------------------------------------------------------------------
# AWS Secrets Manager — centralized, audited secret storage
#
# Disabled by default because some environments restrict the
# secretsmanager:CreateSecret permission. Set enable_secrets_manager = true
# in terraform.tfvars to activate this on a full-permission AWS account.
#
# When disabled, the password is still generated by random_password above
# and injected directly into aws_db_instance (see database.tf). It is never
# written in plain text in the code or committed to Git. It can be retrieved
# using: terraform output -raw db_password
# ---------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "db_credentials" {
  count = var.enable_secrets_manager ? 1 : 0

  name        = "${local.name_prefix}/rds/credentials"
  description = "RDS MariaDB credentials for ${local.name_prefix}"

  # The default aws/secretsmanager KMS key is used for encryption.
  # On a production account with full KMS access, replace this with a
  # customer-managed key (CMK): kms_key_id = aws_kms_key.main.arn

  # Set to 0 for lab environments so the secret can be deleted immediately.
  # Use at least 7 days in production.
  recovery_window_in_days = 0

  tags = {
    Name = "${local.name_prefix}-db-secret"
  }
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  count = var.enable_secrets_manager ? 1 : 0

  secret_id = aws_secretsmanager_secret.db_credentials[0].id

  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_password.result
    engine   = "mariadb"
    dbname   = var.db_name
  })
}
